hopefully the last test

diff --git a/.github/workflows/build-v8-linux.yml b/.github/workflows/build-v8-linux.yml
--- a/.github/workflows/build-v8-linux.yml
+++ b/.github/workflows/build-v8-linux.yml
@@ -67,45 +67,40 @@ jobs:
                 gn gen out/x64.debug --args='v8_target_cpu="x64" target_cpu="x64" is_debug=true symbol_level=2 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true'
                 ninja -C out/x64.debug v8_monolith v8_hello_world
 
-        #  - name: Build V8 Linux x64 Release
-        #    shell: bash
-        #    run: |
-        #        cd v8/v8
-        #        gn gen out/x64.release --args='v8_target_cpu="x64" target_cpu="x64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
-        #        ninja -C out/x64.release v8_monolith v8_hello_world
+          - name: Build V8 Linux x64 Release
+            shell: bash
+            run: |
+                cd v8/v8
+                gn gen out/x64.release --args='v8_target_cpu="x64" target_cpu="x64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
+                ninja -C out/x64.release v8_monolith v8_hello_world
 
-        #  - name: Test Product
-        #    shell: bash
-        #    run: |
-        #        set -e
-        #        chmod +x ./v8/v8/out/x64.debug/v8_hello_world
-        #        chmod +x ./v8/v8/out/x64.release/v8_hello_world
-        #        output1=$(./v8/v8/out/x64.debug/v8_hello_world)
-        #        if [[ "$output1" == "Hello, World!"* ]]; then
-        #            echo "Debug test passed."
-        #        else
-        #            echo "Test failure: output is $output1"
-        #            exit 1
-        #        fi
-        #        output2=$(./v8/v8/out/x64.release/v8_hello_world)
-        #        if [[ "$output2" == "Hello, World!"* ]]; then
-        #            echo "Release test passed."
-        #        else
-        #            echo "Test failure: output is $output2"
-        #            exit 1
-        #        fi
+          - name: Test Product
+            shell: bash
+            run: |
+                set -e
+                chmod +x ./v8/v8/out/x64.debug/v8_hello_world
+                chmod +x ./v8/v8/out/x64.release/v8_hello_world
+                output1=$(./v8/v8/out/x64.debug/v8_hello_world)
+                if [[ "$output1" == "Hello, World!"* ]]; then
+                    echo "Debug test passed."
+                else
+                    echo "Test failure: output is $output1"
+                    exit 1
+                fi
+                output2=$(./v8/v8/out/x64.release/v8_hello_world)
+                if [[ "$output2" == "Hello, World!"* ]]; then
+                    echo "Release test passed."
+                else
+                    echo "Test failure: output is $output2"
+                    exit 1
+                fi
 
           - name: Compress Product
             shell: bash
             run: |
                 echo "${{inputs.version}}" >> VERSION
-                sudo apt-get update && sudo apt-get install -y p7zip-full
-                cd v8/v8/out/x64.debug
-                ls
-                cd obj
-                ls
-                7z a v8_linux_x64_debug.7z ./v8/v8/out/x64.debug/obj/v8_monolith.a ./v8/v8/include VERSION
-                7z a v8_linux_x64_release.7z ./v8/v8/out/x64.release/obj/v8_monolith.a ./v8/v8/include VERSION
+                7z a v8_linux_x64_debug.7z ./v8/v8/out/x64.debug/obj/libv8_monolith.a ./v8/v8/include VERSION
+                7z a v8_linux_x64_release.7z ./v8/v8/out/x64.release/obj/libv8_monolith.a ./v8/v8/include VERSION
         
           - name: Upload Archive
             uses: actions/upload-artifact@v4
@@ -172,9 +167,8 @@ jobs:
             shell: bash
             run: |
                 echo "${{inputs.version}}" >> VERSION
-                sudo apt-get update && sudo apt-get install -y p7zip-full
-                7z a v8_linux_arm64_debug.7z ./v8/v8/out/arm64.debug/obj/v8_monolith.a ./v8/v8/include VERSION
-                7z a v8_linux_arm64_release.7z ./v8/v8/out/arm64.release/obj/v8_monolith.a ./v8/v8/include VERSION
+                7z a v8_linux_arm64_debug.7z ./v8/v8/out/arm64.debug/obj/libv8_monolith.a ./v8/v8/include VERSION
+                7z a v8_linux_arm64_release.7z ./v8/v8/out/arm64.release/obj/libv8_monolith.a ./v8/v8/include VERSION
         
           - name: Upload Archive
             uses: actions/upload-artifact@v4
