use arm64 to test

diff --git a/.github/workflows/build-v8-macos.yml b/.github/workflows/build-v8-macos.yml
--- a/.github/workflows/build-v8-macos.yml
+++ b/.github/workflows/build-v8-macos.yml
@@ -51,27 +51,6 @@ jobs:
                 gn gen out/x64.release --args='v8_target_cpu="x64" target_cpu="x64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
                 ninja -C out/x64.release v8_monolith v8_hello_world
 
-          - name: Test Product
-            shell: bash
-            run: |
-                set -e
-                chmod +x ./v8/v8/out/x64.debug/v8_hello_world
-                chmod +x ./v8/v8/out/x64.release/v8_hello_world
-                output1=$(./v8/v8/out/x64.debug/v8_hello_world)
-                if [[ "$output1" == "Hello, World!"* ]]; then
-                    echo "Debug test passed."
-                else
-                    echo "Test failure: output is $output1"
-                    exit 1
-                fi
-                output2=$(./v8/v8/out/x64.release/v8_hello_world)
-                if [[ "$output2" == "Hello, World!"* ]]; then
-                    echo "Release test passed."
-                else
-                    echo "Test failure: output is $output2"
-                    exit 1
-                fi
-
           - name: Compress Product
             shell: bash
             run: |
@@ -122,6 +101,27 @@ jobs:
                 cd v8/v8
                 gn gen out/arm64.release --args='v8_target_cpu="arm64" target_cpu="arm64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
                 ninja -C out/arm64.release v8_monolith v8_hello_world
+
+          - name: Test Product
+            shell: bash
+            run: |
+                set -e
+                chmod +x ./v8/v8/out/x64.debug/v8_hello_world
+                chmod +x ./v8/v8/out/x64.release/v8_hello_world
+                output1=$(./v8/v8/out/x64.debug/v8_hello_world)
+                if [[ "$output1" == "Hello, World!"* ]]; then
+                    echo "Debug test passed."
+                else
+                    echo "Test failure: output is $output1"
+                    exit 1
+                fi
+                output2=$(./v8/v8/out/x64.release/v8_hello_world)
+                if [[ "$output2" == "Hello, World!"* ]]; then
+                    echo "Release test passed."
+                else
+                    echo "Test failure: output is $output2"
+                    exit 1
+                fi
 
           - name: Compress Product
             shell: bash
