finishing test

diff --git a/.github/workflows/build-v8-macos.yml b/.github/workflows/build-v8-macos.yml
--- a/.github/workflows/build-v8-macos.yml
+++ b/.github/workflows/build-v8-macos.yml
@@ -6,6 +6,9 @@ on:
             commit:
                 type: string
                 required: true
+        outputs:
+            runid:
+                value: ${{github.run_id}}
     workflow_dispatch:
         inputs:
             commit:
@@ -13,7 +16,125 @@ on:
                 required: true
 
 jobs:
-    build:
+    build-mac-x64:
         runs-on: macos-latest
         steps:
-          - run: echo 1
+
+          - name: Checkout This Repo
+            uses: actions/checkout@v4
+            with:
+                clean: true
+                fetch-depth: 1
+
+          - name: Check Depot Tools
+            uses: newkdev/setup-depot-tools@v1.0.1
+
+          - name: Checkout V8 Source Code
+            shell: bash
+            run: |
+                mkdir v8
+                cd v8
+                fetch v8
+                gclient sync
+
+          - name: Build V8 MacOS x64 Debug
+            shell: bash
+            run: |
+                cd v8/v8
+                gn gen out/x64.debug --args='v8_target_cpu="x64" target_cpu="x64" is_debug=true symbol_level=2 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true'
+                ninja -C out/x64.debug v8_monolith v8_hello_world
+
+          - name: Build V8 MacOS x64 Release
+            shell: bash
+            run: |
+                cd v8/v8
+                gn gen out/x64.release --args='v8_target_cpu="x64" target_cpu="x64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
+                ninja -C out/x64.release v8_monolith v8_hello_world
+
+          - name: Test Product
+            shell: bash
+            run: |
+                set -e
+                chmod +x ./v8/v8/out/x64.debug/v8_hello_world
+                chmod +x ./v8/v8/out/x64.release/v8_hello_world
+                output1=$(./v8/v8/out/x64.debug/v8_hello_world)
+                if [[ "$output1" == "Hello, World!"* ]]; then
+                    echo "Debug test passed."
+                else
+                    echo "Test failure: output is $output1"
+                    exit 1
+                fi
+                output2=$(./v8/v8/out/x64.release/v8_hello_world)
+                if [[ "$output2" == "Hello, World!"* ]]; then
+                    echo "Release test passed."
+                else
+                    echo "Test failure: output is $output2"
+                    exit 1
+                fi
+
+          - name: Compress Product
+            shell: bash
+            run: |
+                echo "${{inputs.commit}}" >> commit.txt
+                brew install p7zip
+                7z a v8_macos_x64_debug.7z ./v8/v8/out/x64.debug/obj/v8_monolith.lib ./v8/v8/include commit.txt
+                7z a v8_macos_x64_release.7z ./v8/v8/out/x64.release/obj/v8_monolith.lib ./v8/v8/include commit.txt
+        
+          - name: Upload Archive
+            uses: actions/upload-artifact@v4
+            with:
+                name: v8_macos_x64
+                path: |
+                    *.7z
+                retention-days: 7
+
+    build-macos-arm64:
+        runs-on: macos-latest
+        steps:
+
+          - name: Checkout This Repo
+            uses: actions/checkout@v4
+            with:
+                clean: true
+                fetch-depth: 1
+
+          - name: Check Depot Tools
+            uses: newkdev/setup-depot-tools@v1.0.1
+
+          - name: Checkout V8 Source Code
+            shell: bash
+            run: |
+                mkdir v8
+                cd v8
+                fetch v8
+                gclient sync
+
+          - name: Build V8 MacOS arm64 Debug
+            shell: bash
+            run: |
+                cd v8/v8
+                gn gen out/arm64.debug --args='v8_target_cpu="arm64" target_cpu="arm64" is_debug=true symbol_level=2 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true'
+                ninja -C out/arm64.debug v8_monolith v8_hello_world
+
+          - name: Build V8 MacOS arm64 Release
+            shell: bash
+            run: |
+                cd v8/v8
+                gn gen out/arm64.release --args='v8_target_cpu="arm64" target_cpu="arm64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
+                ninja -C out/arm64.release v8_monolith v8_hello_world
+
+          - name: Compress Product
+            shell: bash
+            run: |
+                echo "${{inputs.commit}}" >> commit.txt
+                brew install p7zip
+                7z a v8_macos_arm64_debug.7z ./v8/v8/out/arm64.debug/obj/v8_monolith.lib ./v8/v8/include commit.txt
+                7z a v8_macos_arm64_release.7z ./v8/v8/out/arm64.release/obj/v8_monolith.lib ./v8/v8/include commit.txt
+        
+          - name: Upload Archive
+            uses: actions/upload-artifact@v4
+            with:
+                name: v8_macos_arm64
+                path: |
+                    *.7z
+                retention-days: 7
